#!/usr/bin/env bash
# Stop charging via ACPI WMI method. Requires root.
set -euo pipefail
echo '\_SB.WMID.SBCO BUFQ{0x00, 0x05, 0x00, 0x00}' | sudo tee /proc/acpi/call >/dev/null
echo "Charging INHIBITED"
